### ISSUE TITLE
Add more information to UI

### ISSUE THREAD

**Issue by leiDnedyA** [leiDnedyA/qr-image-drop#54]
We recently got a review from a senior engineer with 15+ YOE, and a big part of his critique is that the site didn't clearly present a use case (i.e why not just email images to yourself or use something like discord?)

Our main use case compared to other options is literally just to get images from your phone to your computer as fast as possible, and I feel that we need to make that clearer to the user.

Here's what I propose we do
1. Rather than having the information button in the corner, have a link to an FAQ page near the top with the following info
    - Include file size restrictions
    - Include allowed filetypes
    - Give an explanation of the purpose of the site
    - Explain what the refresh and reset session buttons do, and how sessions work
    - Say how long sessions last for
    - Explain what happens to files after the session ends
    - Add contact info in case users find bugs or have ideas for features
2. Rather than having the header say "Upload and Share Files", it would be better to say "Transfer files fast", as that's really the goal of the application

If anyone's curious, I'll add a PDF of the email as an attachment to the PR!
[Gmail - HN Offer.pdf](https://github.com/leiDnedyA/qr-image-drop/files/15390525/Gmail.-.HN.Offer.pdf)

\- Ayden

**Comment by gaiborjosue** [comment]
Hello @leiDnedyA thanks for attaching the feedback. I am working on this right now :)

**Comment by gaiborjosue** [comment]
Hello,

As suggested on the issue, I've made the following updates to the UI:

1.- The menu header now includes a new subheader, and I've added a new button for the FAQ. I used the same buttons to keep the design synergy. However, feel free to suggest otherwise.

![image](https://github.com/leiDnedyA/qr-image-drop/assets/78832141/e9f0527a-7a4b-496e-8563-d7315377433b)


2.- Added a new page for the FAQ and removed the "i" icon on the bottom of the index. This FAQ page contains the answers to the questions proposed by HN. The banner is animated btw, but I also have a static svg version on the assets folder.

![image](https://github.com/leiDnedyA/qr-image-drop/assets/78832141/81432cd3-fe52-48b6-8128-44c23ad6a464)


Feel free to suggest changes to the UI or anything else :)
